### ISSUE TITLE
Format issues in css

### ISSUE THREAD

**Issue by Captain-Coconut** [IleanaEscobar/flixster_starter#1]
https://github.com/IleanaEscobar/flixster_starter/blob/2c805ab75a3b240dbd1382412b57b7d2bfa6be18/style.css#L1

1. Blank lines were used inconsistently across the file.
2. Fields in a bracket should be ordered alphabetically for readability. 

You can perhaps use VS code's auto format function to easily address these without much hassle. :)

**Comment by IleanaEscobar** [comment]
fixed.
