### ISSUE TITLE
Multiple style issues (explain in details)

### ISSUE THREAD

**Issue by Captain-Coconut** [IleanaEscobar/flixster_starter#3]
https://github.com/IleanaEscobar/flixster_starter/blob/2c805ab75a3b240dbd1382412b57b7d2bfa6be18/script.js#L13

Overall you did a great job in writing this. The code logic is very clear. So my comments are mostly just regarding styles and formats. Since there are multiple occurrences for each issues, I am just gonna summarize them here, instead of commenting on each line:

(1) Some variables are not used, for example 'api_key'.
(2) Variable name styles are not consistent. In some places you camel cases, in other places you used snake cases.
(3) Some variables are not explicitly defined (which I think is probably ok but it is perhaps better to define them).
(4) Some lines are too long, some blanks are missing and some indentation is not consistent. These make readability not good enough.
(5) Both single quotes and double quotes formats are used in the code.

I suggest you paste this into VSCode and many issues can be automatically fixed.

**Comment by IleanaEscobar** [comment]
fixed.
